site_name: Documentation for HSDA Metadata
site_url: https://fair-archaeometry-lab.github.io/mkdoc-hsda-metadata/
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle: 
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

  icon:
    admonition:
      note: material/note

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage 
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
      
